import { BaseProvider } from "./interface.js";
import type { ChatRequest, TokenChunk } from "../types.js";

export class LocalLlamaProvider extends BaseProvider {
  constructor(private readonly baseUrl: string) {
    super();
  }

  async *generateStream(request: ChatRequest): AsyncIterable<TokenChunk> {
    const response = await fetch(`${this.baseUrl}/completion`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        prompt: request.message,
        n_predict: 256,
        temperature: 0.4,
        stream: false
      })
    });

    if (!response.ok) {
      const body = await response.text();
      throw new Error(`llama.cpp completion failed (${response.status}): ${body}`);
    }

    const payload = (await response.json()) as { content?: string };
    const output = payload.content?.trim() || "No output generated by local model.";
    yield* this.streamWords(output, 6);
  }
}
