import { BaseProvider } from "./interface.js";
import type { ChatRequest, TokenChunk } from "../types.js";

export class MockProvider extends BaseProvider {
  async *generateStream(request: ChatRequest): AsyncIterable<TokenChunk> {
    const text = `Acknowledged. Message received: ${request.message}. This response is generated by mock provider for deterministic TTFT validation.`;
    yield* this.streamWords(text, 8);
  }
}
