#!/usr/bin/env node
/**
 * generate-cloned-greeting.ts — regenerates the spoken greeting from the
 * introduction the panel actually displays.
 *
 * Usage:
 *   ELEVENLABS_API_KEY=sk_... ELEVENLABS_VOICE_ID=abc123 \
 *     npx tsx scripts/generate-cloned-greeting.ts
 *
 * The script used to carry its own copy of the script text. That is exactly how
 * the two drifted: the on-screen introduction was rewritten to the
 * employer-research copy while the MP3 kept speaking the old "Hi, I'm Mini Vic"
 * line, and an independent review caught a visitor reading one introduction and
 * hearing another (ADV-REVIEW-20260905, G-M2). There is now one definition —
 * `GREETING.hiring` in app/data/miniVicKnowledge.ts — and both the component
 * and this script import it.
 *
 * Each run writes, in one pass, so nothing can be half-updated:
 *   - public/assets/minivic-greeting.mp3       the audio
 *   - public/assets/minivic-greeting.txt       the words it speaks, verbatim
 *   - app/data/generated/greeting-asset.ts     the digest MiniVicBot asserts at
 *                                              runtime (TC-FR-VOICE)
 *   - app/data/generated/greeting-alignment.ts when each character was spoken
 *
 * The alignment comes from `/with-timestamps`, i.e. from the *same call* that
 * renders the MP3, and that is not a convenience. ElevenLabs synthesis is not
 * reproducible across calls: an alignment fetched later against the committed
 * MP3 would describe a different render, and the mouth would drift from the
 * voice without bound and without anything failing. Both artefacts therefore
 * carry the same `sha256` of the same bytes, and scripts/build/greeting_envelope.mjs
 * FATALs at build time if the two ever disagree (MINIVIC-AVATAR-v1.md §2.2).
 *
 * ELEVENLABS_VOICE_ID may name an instant-voice-clone the account's plan no
 * longer permits. In that case the run reports the HTTP status and stops rather
 * than silently substituting a voice: pass a chosen premade voice id explicitly
 * so the decision is recorded by whoever makes it.
 *
 * That is what happened on 2026-09-06. The configured ELEVENLABS_VOICE_ID names
 * a `cloned` voice and the API answered `401 ivc_not_permitted` before any
 * synthesis, so the run that produced the committed MP3 passed the premade voice
 * `IKne3meq5aSn9XLyUdCD` ("Charlie", GET /v1/voices → category `premade`,
 * labels `gender: male`, `accent: australian`) explicitly. It is the only
 * Australian male voice in the account's premade set, and the panel already
 * tells the visitor the voice is stock, so nobody is invited to hear it as his.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as crypto from "node:crypto";

import { GREETING } from "../app/data/miniVicKnowledge";

/**
 * The introduction, read from the single definition the panel renders. `hiring`
 * is the persona the panel opens in, so it is the one a visitor hears.
 */
const GREETING_TEXT = GREETING.hiring;

const ELEVENLABS_API_URL = "https://api.elevenlabs.io/v1/text-to-speech";
/** The one encoding the site ships; also what the alignment is measured against. */
const OUTPUT_FORMAT = "mp3_44100_128";
const REPO_ROOT = path.resolve(__dirname, "..");

/** Writes the digest + transcript module MiniVicBot imports. */
function writeGeneratedModule(hash: string, text: string): string {
  const target = path.join(REPO_ROOT, "app", "data", "generated", "greeting-asset.ts");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(
    target,
    `/**\n` +
      ` * GENERATED by scripts/generate-cloned-greeting.ts — do not edit.\n` +
      ` *\n` +
      ` * The digest of public/assets/minivic-greeting.mp3 as the generation run wrote\n` +
      ` * it, alongside the exact words that run spoke. Both are emitted in the same\n` +
      ` * pass as the audio, so the runtime assertion (TC-VOICE-01 reads the digest off\n` +
      ` * \`window.__CLONED_VOICE_GREETING_HASH__\`) can never sit one regeneration\n` +
      ` * behind the file it describes — the defect the reviewer measured on\n` +
      ` * 2026-09-05, where the MP3 still spoke the old script while the on-screen\n` +
      ` * introduction had been rewritten.\n` +
      ` */\n` +
      `export const greetingAudioSha256 = '${hash}';\n\n` +
      `/** Words spoken in the recording above — always \`GREETING.hiring\`. */\n` +
      `export const greetingSpokenText =\n  ${JSON.stringify(text)};\n`,
  );
  return target;
}

/** One character of the greeting, and the window the voice spent on it. */
interface ElevenLabsAlignment {
  characters: string[];
  character_start_times_seconds: number[];
  character_end_times_seconds: number[];
}

/** Writes the character alignment lib/visemeSchedule.ts turns into mouth cues. */
function writeAlignmentModule(hash: string, alignment: ElevenLabsAlignment): string {
  const target = path.join(REPO_ROOT, "app", "data", "generated", "greeting-alignment.ts");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  const numbers = (values: number[]) => `[\n    ${values.join(",\n    ")},\n  ]`;
  fs.writeFileSync(
    target,
    `/**\n` +
      ` * GENERATED by scripts/generate-cloned-greeting.ts — do not edit.\n` +
      ` *\n` +
      ` * When each character of public/assets/minivic-greeting.mp3 was spoken, as\n` +
      ` * ElevenLabs' /with-timestamps endpoint reported it in the same call that\n` +
      ` * rendered those bytes. lib/visemeSchedule.ts turns this into the cue list the\n` +
      ` * mouth is driven from.\n` +
      ` *\n` +
      ` * "sourceSha256" is the SHA-256 of that MP3 and equals "greetingAudioSha256"\n` +
      ` * in ./greeting-asset.ts. scripts/build/greeting_envelope.mjs asserts the two\n` +
      ` * are equal on every build: synthesis is not reproducible across calls, so an\n` +
      ` * alignment that does not name the exact render it came from is an alignment\n` +
      ` * that can be applied to the wrong audio (MINIVIC-AVATAR-v1.md §2.2).\n` +
      ` */\n` +
      `export const greetingAlignment = {\n` +
      `  /** One entry per character of "greetingSpokenText", in order. */\n` +
      `  characters: ${JSON.stringify(alignment.characters)},\n` +
      `  /** Seconds from the top of the audio, never rounded. */\n` +
      `  characterStartTimesSeconds: ${numbers(alignment.character_start_times_seconds)},\n` +
      `  /** Seconds from the top of the audio, never rounded. */\n` +
      `  characterEndTimesSeconds: ${numbers(alignment.character_end_times_seconds)},\n` +
      `  /** SHA-256 of the MP3 these times describe; equals greetingAudioSha256. */\n` +
      `  sourceSha256: '${hash}',\n` +
      `};\n`,
  );
  return target;
}

async function main() {
  const apiKey = process.env.ELEVENLABS_API_KEY;
  const voiceId = process.env.ELEVENLABS_VOICE_ID;

  if (!apiKey) {
    console.error(
      "❌  Missing ELEVENLABS_API_KEY. Set it in the environment.\n" +
        "    Get your API key at: https://elevenlabs.io/app/settings/api-keys",
    );
    process.exit(1);
  }

  if (!voiceId) {
    console.error(
      "❌  Missing ELEVENLABS_VOICE_ID.\n" +
        "    Create a cloned voice at https://elevenlabs.io/app/voice-lab\n" +
        "    then pass its ID as ELEVENLABS_VOICE_ID.",
    );
    process.exit(1);
  }

  console.log("🎤  Generating the spoken greeting from GREETING.hiring...");
  console.log(`    Voice ID: ${voiceId}`);
  console.log(`    Characters: ${GREETING_TEXT.length}`);

  const started = Date.now();

  const response = await fetch(
    `${ELEVENLABS_API_URL}/${encodeURIComponent(voiceId)}/with-timestamps` +
      `?output_format=${OUTPUT_FORMAT}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "xi-api-key": apiKey,
      },
      body: JSON.stringify({
        text: GREETING_TEXT,
        model_id: "eleven_turbo_v2",
        voice_settings: {
          stability: 0.5,
          similarity_boost: 0.75,
          style: 0.1,
          use_speaker_boost: true,
        },
      }),
    },
  );

  console.log(`    HTTP ${response.status} ${response.statusText}`);

  if (!response.ok) {
    const errorText = await response.text().catch(() => "unknown error");
    console.error(`❌  ElevenLabs returned ${response.status}: ${errorText}`);
    console.error(
      "    No asset was written. If the voice id is rejected, choose a voice from\n" +
        "    GET https://api.elevenlabs.io/v1/voices and pass it as ELEVENLABS_VOICE_ID.",
    );
    process.exit(1);
  }

  const payload = (await response.json()) as {
    audio_base64?: string;
    alignment?: ElevenLabsAlignment;
  };
  const elapsed = Date.now() - started;

  if (typeof payload.audio_base64 !== "string" || payload.audio_base64.length === 0) {
    console.error("❌  /with-timestamps returned no audio_base64. Nothing was written.");
    process.exit(1);
  }
  const alignment = payload.alignment;
  if (
    !alignment ||
    !Array.isArray(alignment.characters) ||
    !Array.isArray(alignment.character_start_times_seconds) ||
    !Array.isArray(alignment.character_end_times_seconds) ||
    alignment.characters.length !== alignment.character_start_times_seconds.length ||
    alignment.characters.length !== alignment.character_end_times_seconds.length
  ) {
    console.error(
      "❌  /with-timestamps returned no usable alignment. Nothing was written: an MP3\n" +
        "    without the alignment of its own render cannot be lip-synced, and a later\n" +
        "    call would describe different audio.",
    );
    process.exit(1);
  }

  const audioBuffer = Buffer.from(payload.audio_base64, "base64");

  const outDir = path.join(REPO_ROOT, "public", "assets");
  fs.mkdirSync(outDir, { recursive: true });

  const mp3Path = path.join(outDir, "minivic-greeting.mp3");
  fs.writeFileSync(mp3Path, audioBuffer);

  // The transcript is what makes the drift checkable without listening to the
  // audio: tests/minivic_greeting.test.mjs compares it to GREETING.hiring.
  const txtPath = path.join(outDir, "minivic-greeting.txt");
  fs.writeFileSync(txtPath, `${GREETING_TEXT}\n`);

  const hash = crypto.createHash("sha256").update(audioBuffer).digest("hex");
  const modulePath = writeGeneratedModule(hash, GREETING_TEXT);
  const alignmentPath = writeAlignmentModule(hash, alignment);

  console.log(`✅  Done in ${elapsed}ms`);
  console.log(`    Audio:      ${mp3Path} (${(audioBuffer.length / 1024).toFixed(1)} KB)`);
  console.log(`    Transcript: ${txtPath}`);
  console.log(`    Module:     ${modulePath}`);
  console.log(`    Alignment:  ${alignmentPath} (${alignment.characters.length} characters)`);
  console.log(`    SHA-256:    ${hash}`);
}

main().catch((err) => {
  console.error("❌  Failed to generate the greeting:");
  console.error(err);
  process.exit(1);
});
