#!/usr/bin/env node
/**
 * generate-cloned-greeting.ts — regenerates the spoken greeting from the
 * introduction the panel actually displays.
 *
 * Usage:
 *   ELEVENLABS_API_KEY=sk_... ELEVENLABS_VOICE_ID=abc123 \
 *     npx tsx scripts/generate-cloned-greeting.ts
 *
 * The script used to carry its own copy of the script text. That is exactly how
 * the two drifted: the on-screen introduction was rewritten to the
 * employer-research copy while the MP3 kept speaking the old "Hi, I'm Mini Vic"
 * line, and an independent review caught a visitor reading one introduction and
 * hearing another (ADV-REVIEW-20260905, G-M2). There is now one definition —
 * `GREETING.hiring` in app/data/miniVicKnowledge.ts — and both the component
 * and this script import it.
 *
 * Each run writes, in one pass, so nothing can be half-updated:
 *   - public/assets/minivic-greeting.mp3   the audio
 *   - public/assets/minivic-greeting.txt   the words it speaks, verbatim
 *   - app/data/generated/greeting-asset.ts the digest MiniVicBot asserts at
 *                                          runtime (TC-FR-VOICE)
 *
 * ELEVENLABS_VOICE_ID may name an instant-voice-clone the account's plan no
 * longer permits. In that case the run reports the HTTP status and stops rather
 * than silently substituting a voice: pass a chosen premade voice id explicitly
 * so the decision is recorded by whoever makes it.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as crypto from "node:crypto";

import { GREETING } from "../app/data/miniVicKnowledge";

/**
 * The introduction, read from the single definition the panel renders. `hiring`
 * is the persona the panel opens in, so it is the one a visitor hears.
 */
const GREETING_TEXT = GREETING.hiring;

const ELEVENLABS_API_URL = "https://api.elevenlabs.io/v1/text-to-speech";
const REPO_ROOT = path.resolve(__dirname, "..");

/** Writes the digest + transcript module MiniVicBot imports. */
function writeGeneratedModule(hash: string, text: string): string {
  const target = path.join(REPO_ROOT, "app", "data", "generated", "greeting-asset.ts");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(
    target,
    `/**\n` +
      ` * GENERATED by scripts/generate-cloned-greeting.ts — do not edit.\n` +
      ` *\n` +
      ` * The digest of public/assets/minivic-greeting.mp3 as the generation run wrote\n` +
      ` * it, alongside the exact words that run spoke. Both are emitted in the same\n` +
      ` * pass as the audio, so the runtime assertion (TC-VOICE-01 reads the digest off\n` +
      ` * \`window.__CLONED_VOICE_GREETING_HASH__\`) can never sit one regeneration\n` +
      ` * behind the file it describes — the defect the reviewer measured on\n` +
      ` * 2026-09-05, where the MP3 still spoke the old script while the on-screen\n` +
      ` * introduction had been rewritten.\n` +
      ` */\n` +
      `export const greetingAudioSha256 = '${hash}';\n\n` +
      `/** Words spoken in the recording above — always \`GREETING.hiring\`. */\n` +
      `export const greetingSpokenText =\n  ${JSON.stringify(text)};\n`,
  );
  return target;
}

async function main() {
  const apiKey = process.env.ELEVENLABS_API_KEY;
  const voiceId = process.env.ELEVENLABS_VOICE_ID;

  if (!apiKey) {
    console.error(
      "❌  Missing ELEVENLABS_API_KEY. Set it in the environment.\n" +
        "    Get your API key at: https://elevenlabs.io/app/settings/api-keys",
    );
    process.exit(1);
  }

  if (!voiceId) {
    console.error(
      "❌  Missing ELEVENLABS_VOICE_ID.\n" +
        "    Create a cloned voice at https://elevenlabs.io/app/voice-lab\n" +
        "    then pass its ID as ELEVENLABS_VOICE_ID.",
    );
    process.exit(1);
  }

  console.log("🎤  Generating the spoken greeting from GREETING.hiring...");
  console.log(`    Voice ID: ${voiceId}`);
  console.log(`    Characters: ${GREETING_TEXT.length}`);

  const started = Date.now();

  const response = await fetch(`${ELEVENLABS_API_URL}/${encodeURIComponent(voiceId)}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "xi-api-key": apiKey,
    },
    body: JSON.stringify({
      text: GREETING_TEXT,
      model_id: "eleven_turbo_v2",
      voice_settings: {
        stability: 0.5,
        similarity_boost: 0.75,
        style: 0.1,
        use_speaker_boost: true,
      },
      output_format: "mp3_44100_128",
    }),
  });

  console.log(`    HTTP ${response.status} ${response.statusText}`);

  if (!response.ok) {
    const errorText = await response.text().catch(() => "unknown error");
    console.error(`❌  ElevenLabs returned ${response.status}: ${errorText}`);
    console.error(
      "    No asset was written. If the voice id is rejected, choose a voice from\n" +
        "    GET https://api.elevenlabs.io/v1/voices and pass it as ELEVENLABS_VOICE_ID.",
    );
    process.exit(1);
  }

  const audioBuffer = Buffer.from(await response.arrayBuffer());
  const elapsed = Date.now() - started;

  const outDir = path.join(REPO_ROOT, "public", "assets");
  fs.mkdirSync(outDir, { recursive: true });

  const mp3Path = path.join(outDir, "minivic-greeting.mp3");
  fs.writeFileSync(mp3Path, audioBuffer);

  // The transcript is what makes the drift checkable without listening to the
  // audio: tests/minivic_greeting.test.mjs compares it to GREETING.hiring.
  const txtPath = path.join(outDir, "minivic-greeting.txt");
  fs.writeFileSync(txtPath, `${GREETING_TEXT}\n`);

  const hash = crypto.createHash("sha256").update(audioBuffer).digest("hex");
  const modulePath = writeGeneratedModule(hash, GREETING_TEXT);

  console.log(`✅  Done in ${elapsed}ms`);
  console.log(`    Audio:      ${mp3Path} (${(audioBuffer.length / 1024).toFixed(1)} KB)`);
  console.log(`    Transcript: ${txtPath}`);
  console.log(`    Module:     ${modulePath}`);
  console.log(`    SHA-256:    ${hash}`);
}

main().catch((err) => {
  console.error("❌  Failed to generate the greeting:");
  console.error(err);
  process.exit(1);
});
