#!/usr/bin/env node
/**
 * generate-cloned-greeting.ts — Build-time script to generate the cloned-voice
 * greeting MP3 using ElevenLabs voice clone of Vikram.
 *
 * Usage:
 *   ELEVENLABS_API_KEY=sk_... ELEVENLABS_VOICE_ID=abc123 \
 *     npx tsx scripts/generate-cloned-greeting.ts
 *
 * This regenerates public/assets/minivic-greeting.mp3 and records its
 * SHA-256 hash for the TC-FR-VOICE quality gate (assertable in e2e tests).
 * The hash is written to .env.greeting-hash and can be imported by the
 * Next.js build to inject CLONED_VOICE_GREETING_HASH at compile time.
 *
 * Tier 1 (static default): this MP3 is the DEFAULT greeting on static
 * Firebase hosting — no API key ships to the browser.
 *
 * Tier 2 (dynamic): the live ElevenLabs WebSocket uses the same voice ID
 * at runtime through the services/api-gateway Docker stack.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as crypto from "node:crypto";

const GREETING_TEXT =
  "Hi, I'm Mini Vic — Vikram's AI clone. I can answer questions about his experience delivering AI programs, leading squads, and architecting platforms. Ask me anything about his work at the ATO, ANZ, or the open-source projects on his GitHub. What would you like to know?";

const ELEVENLABS_API_URL = "https://api.elevenlabs.io/v1/text-to-speech";

async function main() {
  const apiKey = process.env.ELEVENLABS_API_KEY;
  const voiceId = process.env.ELEVENLABS_VOICE_ID;

  if (!apiKey) {
    console.error(
      "❌  Missing ELEVENLABS_API_KEY. Set it in the environment.\n" +
        "    Get your API key at: https://elevenlabs.io/app/settings/api-keys",
    );
    process.exit(1);
  }

  if (!voiceId) {
    console.error(
      "❌  Missing ELEVENLABS_VOICE_ID.\n" +
        "    Create a cloned voice at https://elevenlabs.io/app/voice-lab\n" +
        "    then pass its ID as ELEVENLABS_VOICE_ID.",
    );
    process.exit(1);
  }

  console.log("🎤  Generating cloned-voice greeting...");
  console.log(`    Voice ID: ${voiceId}`);
  console.log(`    Text: "${GREETING_TEXT.slice(0, 60)}..."`);

  const started = Date.now();

  try {
    const response = await fetch(`${ELEVENLABS_API_URL}/${encodeURIComponent(voiceId)}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "xi-api-key": apiKey,
      },
      body: JSON.stringify({
        text: GREETING_TEXT,
        model_id: "eleven_turbo_v2",
        voice_settings: {
          stability: 0.5,
          similarity_boost: 0.75,
          style: 0.1,
          use_speaker_boost: true,
        },
        output_format: "mp3_44100_128",
      }),
    });

    if (!response.ok) {
      const errorText = await response.text().catch(() => "unknown error");
      console.error(`❌  ElevenLabs API returned ${response.status}: ${errorText}`);
      process.exit(1);
    }

    const audioBuffer = Buffer.from(await response.arrayBuffer());
    const elapsed = Date.now() - started;

    // Write the MP3 to public/assets
    const outDir = path.resolve(__dirname, "..", "public", "assets");
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, "minivic-greeting.mp3");
    fs.writeFileSync(outPath, audioBuffer);

    // Compute SHA-256 hash for quality gate TC-FR-VOICE
    const hash = crypto.createHash("sha256").update(audioBuffer).digest("hex");

    // Write hash to .env.greeting-hash for build-time injection
    const hashEnvPath = path.resolve(__dirname, "..", ".env.greeting-hash");
    fs.writeFileSync(
      hashEnvPath,
      `# Generated by scripts/generate-cloned-greeting.ts\n` +
        `# DO NOT EDIT — regenerated on every run.\n` +
        `NEXT_PUBLIC_CLONED_VOICE_GREETING_HASH=${hash}\n`,
    );

    console.log(`✅  Done in ${elapsed}ms`);
    console.log(`    File: ${outPath}`);
    console.log(`    Size: ${(audioBuffer.length / 1024).toFixed(1)} KB`);
    console.log(`    SHA-256: ${hash}`);
    console.log(`    Hash file: ${hashEnvPath}`);
    console.log("");
    console.log("📋  Next steps:");
    console.log("    1. Commit the regenerated MP3");
    console.log("    2. Verify the hash in e2e tests (TC-FR-VOICE)");
    console.log("    3. Deploy to Firebase Hosting");
  } catch (err) {
    console.error("❌  Failed to generate greeting:");
    console.error(err);
    process.exit(1);
  }
}

main();
