import { BaseProvider } from "./interface.js";
import type { ChatRequest, TokenChunk } from "../types.js";
import { normalizeProviderError, providerErrorFromResponse } from "../lib/provider-error.js";

export class LocalLlamaProvider extends BaseProvider {
  constructor(private readonly baseUrl: string) {
    super();
  }

  async *generateStream(request: ChatRequest): AsyncIterable<TokenChunk> {
    try {
      const response = await fetch(`${this.baseUrl}/completion`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          prompt: request.message,
          n_predict: 256,
          temperature: 0.35,
          stream: false
        })
      });

      if (!response.ok) {
        throw await providerErrorFromResponse("local-llama", response, "llama.cpp completion failed");
      }

      const payload = (await response.json()) as { content?: string };
      const output = payload.content?.trim() || "No output generated by local model.";
      yield* this.streamWords(output, 6);
    } catch (error) {
      throw normalizeProviderError(error, "local-llama");
    }
  }
}
